"""empty message

Revision ID: 19ad5323d40c
Revises: 5bc9bef84d16
Create Date: 2020-08-25 00:10:09.268923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ad5323d40c'
down_revision = '5bc9bef84d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lists_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lists_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_roles')
    # ### end Alembic commands ###
