"""empty message

Revision ID: 92be4067e5bf
Revises: 6c9a4dfcd77b
Create Date: 2020-08-24 21:11:35.660453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92be4067e5bf'
down_revision = '6c9a4dfcd77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
